workflows:
  android-release:
    name: Android Release
    workflow_id: android-release
    max_build_duration: 60
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          flutter clean
          flutter pub get
      - name: Run tests
        script: flutter test
      - name: Build release APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/.gradle/caches

  ios-release:
    name: iOS Release
    workflow_id: ios-release
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          flutter clean
          flutter pub get
      - name: Run tests
        script: flutter test
      - name: Build unsigned IPA
        script: flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/.gradle/caches

